### ISSUE TITLE
ENVs for autosaving

### ISSUE THREAD

**Issue by ArroganTz** [jsknnr/soulmask-dedicated-server#9]
Can you please add ENVs for autosaving? you hard coded them here https://github.com/jsknnr/soulmask-dedicated-server/blob/main/container/entrypoint.sh#L80

-backup | Specifies the interval for writing the game database to disk (unit: seconds).
-saving | Specifies the interval for writing game objects to the database (unit: seconds).

thank you very much in advance for your work :)

**Comment by jsknnr** [comment]
Sure. I’ll add that today.
________________________________
From: ArroganTz ***@***.***>
Sent: Friday, July 12, 2024 6:12:25 AM
To: jsknnr/soulmask-dedicated-server ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jsknnr/soulmask-dedicated-server] ENVs for autosaving (Issue #9)


Can you please add ENVs for autosaving? you hard coded them here https://github.com/jsknnr/soulmask-dedicated-server/blob/main/container/entrypoint.sh#L80

-backup | Specifies the interval for writing the game database to disk (unit: seconds).
-saving | Specifies the interval for writing game objects to the database (unit: seconds).

**Comment by ArroganTz** [comment]
Thank you!

**Comment by jsknnr** [comment]
New image built and released. Let me know if you have any issues.
